### ISSUE TITLE
Using pgmetrics as a library

### ISSUE THREAD

**Issue by siddharth178** [rapidloop/pgmetrics#13]
in its current shape, pgmetrics is a simple and useful command line tool. but we are not able to use it in our environment today because we already have some monitoring code running and we don't want to add another binary which is only responsible for postgresql monitoring.

ideal solution would be use pgmetrics as a library.

the code is pretty clean and as far as i can understand, if we export `collect`, any other package should be able to use pgmetrics as a library.

**Comment by mdevan** [comment]
Agree.

Ideal approach would be to move the collection part into a package like `github.com/rapidloop/pgmetrics/collector`, and use that from the command-line tool in `github.com/rapidloop/pgmetrics/cmd/pgmetrics`.

**Comment by siddharth178** [comment]
Good to know that you are open to make this. Let me see if I can come up with something on these lines.

**Comment by siddharth178** [comment]
Here is another attempt to get this going.
https://github.com/rapidloop/pgmetrics/pull/15

**Comment by mdevan** [comment]
Sorry for the late reply. Some comments in #15.

**Comment by mdevan** [comment]
Merged and available in master with 25a1800.

**Comment by siddharth178** [comment]
awesome! thanks.  👍
