### ISSUE TITLE
When available on PG 11?

### ISSUE THREAD

**Issue by MichaelDBA** [rapidloop/pgmetrics#18]
I am doing a lot of testing with PG 11 beta4, but pgmetrics does not work for that yet.  Any idea when I can start beta testing pgmetrics for PG 11?

**Comment by mdevan** [comment]
pgmetrics v1.3.0 and above should work with the PG11 beta versions. Can you try with the latest pgmetrics release (v1.4.2), and post any error messages that you see?

**Comment by MichaelDBA** [comment]
Thanks, it worked with pg 11rc1 and pgmetrics 1.4.2
