### ISSUE TITLE
pg_available_extensions query failed

### ISSUE THREAD

**Issue by mc3** [rapidloop/pgmetrics#21]
mc3$ PGSSLMODE=require pgmetrics -h db4 -w -f human -t 60 operations
pgmetrics: pg_available_extensions query failed: sql: Scan error on column index 4, name "comment": unsupported Scan, storing driver.Value type <nil> into type *string
mc3$ psql -h db4 postgres
Timing is on.
SET
Time: 7,236 ms
                       search_path                       
---------------------------------------------------------
 erdb, syslog, pki, dd, ext_ip4r, archiveopteryx, public
(1 row)

Time: 7,388 ms
psql (10.5, server 10.6)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

postgres=# \d pg_available_extensions
         View "pg_catalog.pg_available_extensions"
      Column       | Type | Collation | Nullable | Default 
-------------------+------+-----------+----------+---------
 name              | name |           |          | 
 default_version   | text |           |          | 
 installed_version | text |           |          | 
 comment           | text |           |          | 

postgres=# 
```

**Comment by mdevan** [comment]
Thanks for reporting. With 07cb13e, null value for pg_available_extensions.comment is accepted.
