### ISSUE TITLE
FYI: Chocolatey package

### ISSUE THREAD

**Issue by majkinetor** [rapidloop/pgmetrics#27]
I created chocolatey package for Windows:

https://chocolatey.org/packages/pgmetrics
Src: https://github.com/majkinetor/au-packages/tree/master/pgmetrics

It will be kept up to date via bot within single day from the Github release.

Thanks for the tool.

**Comment by mdevan** [comment]
That's great, thanks!

Is it OK to mention your name and link to the Chocolatey package in the pgmetrics documentation?

**Comment by majkinetor** [comment]
Sure. You can be sure it will always work as long as you release on Github.
