### ISSUE TITLE
AWS RDS PostgreSQL -  pg_ls_dir and pg_current_logfile

### ISSUE THREAD

**Issue by billglennon** [rapidloop/pgmetrics#30]
Hi,

I am trying to use pgmetrics against an AWS PostgreSQL RDS (Version 11.5).

It appears the AWS RDS superuser does not have permissions to pg_ls_dir and pg_current_logfile that I see in the code https://github.com/rapidloop/pgmetrics/blob/master/collector/collect.go.

I am seeing the below error messages on the logfile.
ERROR:  42501: permission denied for function pg_current_logfile
ERROR:  42501: permission denied for function pg_current_logfile

Is there any options I can use to eliminate these errors?

Also, is there any plans to modify this to work on opensource PostgreSQL and AWS RDS PostgreSQL?

Thanks and keep up the great work!

**Comment by mdevan** [comment]
> It appears the AWS RDS superuser does not have permissions to pg_ls_dir and pg_current_logfile

Yes, this is a known issue. It does not hinder the working of pgmetrics however. The only side effect is log pollution.

One change would be to use pg_ls_waldir (v10+) and pg_ls_archive_statusdir (v12+) instead. The other option is to include a flag to skip this step. Or perhaps somehow determine that pgmetrics is connected to AWS RDS and not attempt to call pg_ls_dir/pg_current_logfile if so.

> Also, is there any plans to modify this to work on opensource PostgreSQL and AWS RDS PostgreSQL?

It works with both already. Do you see any errors when you use it?

**Comment by billglennon** [comment]
No, I see no errors. The impact is the "log pollution" as we send our logs to other tools to parse and do analytics. Having cleaner logs would be best so we do not have to write code to clean out the "log pollution".

**Comment by mdevan** [comment]
Fixed by 09811f3, e05e2b9, 4d74213 and 0ab5237. Will be available in next release (v1.9.0), or you can try it directly by compiling from master (run `go get github.com/rapidloop/pgmetrics/cmd/pgmetrics` from an empty directory, builds to `~/go/bin/pgmetrics`).
