### ISSUE TITLE
get all database details without specifying dbnames?

### ISSUE THREAD

**Issue by minusf** [rapidloop/pgmetrics#31]
is there a way to get the detailed, per database report for the whole cluster without the need to specify a list of dbnames?

**Comment by mdevan** [comment]
Not directly, but you can get the list of database names with a separate psql command first:

```shell
DBNAMES=$(psql -Xqtc 'select datname from pg_database where not datistemplate')
pgmetrics -w -o report.txt $DBNAMES
```

**Comment by minusf** [comment]
yeah i was hoping to do something without more scripting, pgmetrics already loops through all db's without the details after all... but you can close it if you want, thanks.
