### ISSUE TITLE
Please, add building instructions

### ISSUE THREAD

**Issue by renich** [rapidloop/pgmetrics#53]
I'm not a go magician. It would be nice to know how to build it myself. 

Thanks! :D

**Comment by mdevan** [comment]
Does this help? https://pgmetrics.io/docs/devel.html

Basically, install Go ([docs](https://go.dev/doc/install)), then do:

```
go install github.com/rapidloop/pgmetrics/cmd/pgmetrics@latest
```

The built binary goes into `~/go/bin`. That's all there is to it.

**Comment by renich** [comment]
Thank you. Didn't see it.
