### ISSUE TITLE
[Feature] Support connect by Keyword/Value Connection Strings

### ISSUE THREAD

**Issue by patsevanton** [rapidloop/pgmetrics#65]
Hello! Thanks for pgmetrics.
Please add connect by Keyword/Value Connection Strings

In the keyword/value format, each parameter setting is in the form keyword = value, with space(s) between settings. Spaces around a setting's equal sign are optional. To write an empty value, or a value containing spaces, surround it with single quotes, for example keyword = 'a value'. Single quotes and backslashes within a value must be escaped with a backslash, i.e., \' and \\.

Example:
```
host=localhost port=5432 dbname=mydb connect_timeout=10
```
https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING

For example my cloud:
```
pgmetrics "host=host \
    port=6432 \
    sslmode=verify-full \
    dbname=dbname \
    user=user \
    target_session_attrs=read-write"
```

**Comment by mdevan** [comment]
Available in v1.17.
