### ISSUE TITLE
Command line improvements

### ISSUE THREAD

**Issue by MichaelDBA** [rapidloop/pgmetrics#7]
First of all, thanks for your new tool!  Here are a few suggestions:

1. Make table output optional or filterable through a new command parameter.  Thousands of tables within a database can cause a lot of unwanted output, perhaps something like --no-tables.

2. Add a schema option to limit table output, --schema  schema1, schema2

3. Put system information output before table output.  That way top level stuff is always at top.

Keep up the good work!

**Comment by mdevan** [comment]
Thanks, good suggestions!

How about a couple of options like:

```
--match-table=PATTERN    include only tables whose name matches PATTERN
--match-schema=PATTERN   include objects only from schema that match PATTERN
```
where PATTERN is a POSIX regular expression, and if it starts with ! then the meaning is inverted (exclude tables/schema). Both options may be used at the same time and works like "AND".

Do you think this will fit your use cases?

**Comment by MichaelDBA** [comment]
The regex stuff is more than I asked for, but sure that'll work for table and schema filtering, but what about the case where I don't want table info?  Now I have to write a regex pattern that will not return anything as opposed to a parameter that just says --no-tables and/or --no-schemas.  How about both?

Also, don't forget about the system info being placed before table output.

**Comment by mdevan** [comment]
OK, let's list down the items.

1. _filter tables_: use an option to include/exclude tables based on regexps
2. _filter schema_: use a repeatable option to only include objects from the specified schema

These two sound good, let's go with it.

I guess the third item is what objects we should collect from a single database. Right now, pgmetrics gets information about:

* tables
* indexes
* sequences
* user function timings
* extensions (this one is not schema-specific)
* disabled triggers

So if we want to collect only some of these types, then there should be an option that specifies that, I think. Like "--collect=tables,indexes" would collect only tables and indexes, or "--collect=all" would collect everything. Thoughts?

And the fourth one is about the report cosmetics, which we'll handle separately in another issue -- it is not related to data collection after all. (And I agree, it makes sense to put it just below the "PostgreSQL Cluster:" section. It gives more context for the rest of the report.)

**Comment by mdevan** [comment]
b38c9ec includes these schema and table selection options:

```
Collection options:
  -c, --schema=REGEXP          collect only from schema(s) matching POSIX regexp
  -C, --exclude-schema=REGEXP  do NOT collect from schema(s) matching POSIX regexp
  -a, --table=REGEXP           collect only from table(s) matching POSIX regexp
  -A, --exclude-table=REGEXP   do NOT collect from table(s) matching POSIX regexp
```

These are similar to `pg_dump`'s options, except that it's based on regexp.

**Comment by mdevan** [comment]
51462e3 includes option to omit the collection of one or more of: tables, indexes, sequences, functions, extensions and triggers.

```
      --omit=WHAT              do NOT collect the items specified as a comma-separated
                                   list of: "tables", "indexes", "sequences",
                                   "functions", "extensions", "triggers"
```

That addresses all the points in this issue, I think. Feel free to reopen this/open another issue if it doesn't.
