### ISSUE TITLE
PGLOCALEDIR issue

### ISSUE THREAD

**Issue by seadba** [rapidloop/pgmetrics#8]
-bash-4.2$ /instance1/dl/pgm/pgmetrics_1.1.0_linux_amd64/pgmetrics --no-password
pgmetrics: pq: unexpected error: "setting PGLOCALEDIR not supported"

i can get past this by unsetting  it but why is this raised?

thanks

**Comment by mdevan** [comment]
Yes, its a bug, duplicate of #5 and fixed in f7d944f. Is available in master, and will be included in the next release.

**Comment by seadba** [comment]
thanks for the fast response and sorry for the dup - this looks like it could be very useful
